name: CI

on: [pull_request]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install imagemagick
        python -m pip install --upgrade pip
        pip install -r windows/requirements.txt

    - name: Run Python script
      run: python windows/RockyConverter.py

  run-bash:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run bash script
      run: |
        sudo apt update
        sudo apt install imagemagick
        bash linux/RockyConverter.sh ./